from PyQt5 import QtCore, QtGui, QtWidgets
from graphics.UIs.buttons_action import *


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 730)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(679, 731))
        MainWindow.setMaximumSize(QtCore.QSize(679, 731))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 681, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.save_as_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.save_as_btn.setMaximumSize(QtCore.QSize(65, 16777215))
        self.save_as_btn.setObjectName("save_as_btn")
        self.gridLayout.addWidget(self.save_as_btn, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 10, 1, 1)
        self.speed_bar = QtWidgets.QSlider(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed_bar.sizePolicy().hasHeightForWidth())
        self.speed_bar.setSizePolicy(sizePolicy)
        self.speed_bar.setMinimumSize(QtCore.QSize(100, 0))
        self.speed_bar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.speed_bar.setOrientation(QtCore.Qt.Horizontal)
        self.speed_bar.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.speed_bar.setObjectName("speed_bar")
        self.gridLayout.addWidget(self.speed_bar, 0, 9, 1, 1)
        self.assemble_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.assemble_btn.setMaximumSize(QtCore.QSize(65, 16777215))
        self.assemble_btn.setCheckable(False)
        self.assemble_btn.setFlat(False)
        self.assemble_btn.setObjectName("assemble_btn")
        self.gridLayout.addWidget(self.assemble_btn, 0, 6, 1, 1)
        self.run_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.run_btn.setMaximumSize(QtCore.QSize(65, 16777215))
        self.run_btn.setObjectName("run_btn")
        self.gridLayout.addWidget(self.run_btn, 0, 7, 1, 1)
        self.open_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.open_btn.setMaximumSize(QtCore.QSize(65, 16777215))
        self.open_btn.setObjectName("open_btn")
        self.gridLayout.addWidget(self.open_btn, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.save_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.save_btn.setMaximumSize(QtCore.QSize(65, 16777215))
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 0, 3, 1, 1)
        self.new_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.new_btn.setMaximumSize(QtCore.QSize(65, 16777215))
        self.new_btn.setObjectName("new_btn")
        self.gridLayout.addWidget(self.new_btn, 0, 1, 1, 1)
        self.step_fwd_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.step_fwd_btn.setMaximumSize(QtCore.QSize(65, 16777215))
        self.step_fwd_btn.setObjectName("step_fwd_btn")
        self.gridLayout.addWidget(self.step_fwd_btn, 0, 8, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-10, 40, 689, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 50, 679, 688))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.edit_tab = QtWidgets.QWidget()
        self.edit_tab.setObjectName("edit_tab")
        self.main_editor = QtWidgets.QTextEdit(self.edit_tab)
        self.main_editor.setGeometry(QtCore.QRect(0, 10, 651, 481))
        self.main_editor.setObjectName("main_editor")
        self.messages_viewer = QtWidgets.QTextBrowser(self.edit_tab)
        self.messages_viewer.setGeometry(QtCore.QRect(80, 500, 541, 151))
        self.messages_viewer.setObjectName("messages_viewer")
        self.messages_label = QtWidgets.QLabel(self.edit_tab)
        self.messages_label.setGeometry(QtCore.QRect(10, 530, 51, 21))
        self.messages_label.setObjectName("messages_label")
        self.clear_btn = QtWidgets.QPushButton(self.edit_tab)
        self.clear_btn.setGeometry(QtCore.QRect(10, 570, 51, 31))
        self.clear_btn.setObjectName("clear_btn")
        self.label_8 = QtWidgets.QLabel(self.edit_tab)
        self.label_8.setGeometry(QtCore.QRect(630, 520, 31, 101))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.edit_tab, "")
        self.execute_tab = QtWidgets.QWidget()
        self.execute_tab.setObjectName("execute_tab")
        self.line_3 = QtWidgets.QFrame(self.execute_tab)
        self.line_3.setGeometry(QtCore.QRect(170, 0, 13, 651))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.execute_tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 171, 651))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_4.setMaximumSize(QtCore.QSize(169, 15))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 2)
        self.opc_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opc_value.sizePolicy().hasHeightForWidth())
        self.opc_value.setSizePolicy(sizePolicy)
        self.opc_value.setMinimumSize(QtCore.QSize(56, 23))
        self.opc_value.setMaximumSize(QtCore.QSize(200, 15))
        self.opc_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.opc_value.setAutoFillBackground(False)
        self.opc_value.setInputMethodHints(QtCore.Qt.ImhNone)
        self.opc_value.setFrameShape(QtWidgets.QFrame.Box)
        self.opc_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.opc_value.setScaledContents(False)
        self.opc_value.setAlignment(QtCore.Qt.AlignCenter)
        self.opc_value.setObjectName("opc_value")
        self.gridLayout_3.addWidget(self.opc_value, 10, 1, 1, 1)
        self.sp_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sp_value.sizePolicy().hasHeightForWidth())
        self.sp_value.setSizePolicy(sizePolicy)
        self.sp_value.setMinimumSize(QtCore.QSize(56, 23))
        self.sp_value.setMaximumSize(QtCore.QSize(200, 15))
        self.sp_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sp_value.setAutoFillBackground(False)
        self.sp_value.setInputMethodHints(QtCore.Qt.ImhNone)
        self.sp_value.setFrameShape(QtWidgets.QFrame.Box)
        self.sp_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sp_value.setScaledContents(False)
        self.sp_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sp_value.setObjectName("sp_value")
        self.gridLayout_3.addWidget(self.sp_value, 6, 1, 1, 1)
        self.mar_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mar_value.sizePolicy().hasHeightForWidth())
        self.mar_value.setSizePolicy(sizePolicy)
        self.mar_value.setMinimumSize(QtCore.QSize(56, 23))
        self.mar_value.setMaximumSize(QtCore.QSize(200, 15))
        self.mar_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mar_value.setAutoFillBackground(False)
        self.mar_value.setInputMethodHints(QtCore.Qt.ImhNone)
        self.mar_value.setFrameShape(QtWidgets.QFrame.Box)
        self.mar_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mar_value.setScaledContents(False)
        self.mar_value.setAlignment(QtCore.Qt.AlignCenter)
        self.mar_value.setObjectName("mar_value")
        self.gridLayout_3.addWidget(self.mar_value, 2, 1, 1, 1)
        self.opc_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opc_label.sizePolicy().hasHeightForWidth())
        self.opc_label.setSizePolicy(sizePolicy)
        self.opc_label.setMinimumSize(QtCore.QSize(56, 23))
        self.opc_label.setMaximumSize(QtCore.QSize(200, 15))
        self.opc_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.opc_label.setAutoFillBackground(False)
        self.opc_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.opc_label.setFrameShape(QtWidgets.QFrame.Box)
        self.opc_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.opc_label.setScaledContents(False)
        self.opc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.opc_label.setObjectName("opc_label")
        self.gridLayout_3.addWidget(self.opc_label, 10, 0, 1, 1)
        self.mdr_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdr_label.sizePolicy().hasHeightForWidth())
        self.mdr_label.setSizePolicy(sizePolicy)
        self.mdr_label.setMinimumSize(QtCore.QSize(56, 23))
        self.mdr_label.setMaximumSize(QtCore.QSize(200, 15))
        self.mdr_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mdr_label.setAutoFillBackground(False)
        self.mdr_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.mdr_label.setFrameShape(QtWidgets.QFrame.Box)
        self.mdr_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mdr_label.setScaledContents(False)
        self.mdr_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mdr_label.setWordWrap(False)
        self.mdr_label.setObjectName("mdr_label")
        self.gridLayout_3.addWidget(self.mdr_label, 3, 0, 1, 1)
        self.mar_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mar_label.sizePolicy().hasHeightForWidth())
        self.mar_label.setSizePolicy(sizePolicy)
        self.mar_label.setMinimumSize(QtCore.QSize(56, 23))
        self.mar_label.setMaximumSize(QtCore.QSize(200, 15))
        self.mar_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mar_label.setAutoFillBackground(False)
        self.mar_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.mar_label.setFrameShape(QtWidgets.QFrame.Box)
        self.mar_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mar_label.setScaledContents(False)
        self.mar_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mar_label.setWordWrap(True)
        self.mar_label.setObjectName("mar_label")
        self.gridLayout_3.addWidget(self.mar_label, 2, 0, 1, 1)
        self.tos_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tos_value.sizePolicy().hasHeightForWidth())
        self.tos_value.setSizePolicy(sizePolicy)
        self.tos_value.setMinimumSize(QtCore.QSize(56, 23))
        self.tos_value.setMaximumSize(QtCore.QSize(200, 15))
        self.tos_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tos_value.setAutoFillBackground(False)
        self.tos_value.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tos_value.setFrameShape(QtWidgets.QFrame.Box)
        self.tos_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tos_value.setScaledContents(False)
        self.tos_value.setAlignment(QtCore.Qt.AlignCenter)
        self.tos_value.setObjectName("tos_value")
        self.gridLayout_3.addWidget(self.tos_value, 9, 1, 1, 1)
        self.cpp_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpp_value.sizePolicy().hasHeightForWidth())
        self.cpp_value.setSizePolicy(sizePolicy)
        self.cpp_value.setMinimumSize(QtCore.QSize(56, 23))
        self.cpp_value.setMaximumSize(QtCore.QSize(200, 15))
        self.cpp_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cpp_value.setAutoFillBackground(False)
        self.cpp_value.setInputMethodHints(QtCore.Qt.ImhNone)
        self.cpp_value.setFrameShape(QtWidgets.QFrame.Box)
        self.cpp_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cpp_value.setScaledContents(False)
        self.cpp_value.setAlignment(QtCore.Qt.AlignCenter)
        self.cpp_value.setObjectName("cpp_value")
        self.gridLayout_3.addWidget(self.cpp_value, 8, 1, 1, 1)
        self.h_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.h_value.sizePolicy().hasHeightForWidth())
        self.h_value.setSizePolicy(sizePolicy)
        self.h_value.setMinimumSize(QtCore.QSize(56, 23))
        self.h_value.setMaximumSize(QtCore.QSize(112, 15))
        self.h_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.h_value.setAutoFillBackground(False)
        self.h_value.setInputMethodHints(QtCore.Qt.ImhNone)
        self.h_value.setFrameShape(QtWidgets.QFrame.Box)
        self.h_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.h_value.setScaledContents(False)
        self.h_value.setAlignment(QtCore.Qt.AlignCenter)
        self.h_value.setObjectName("h_value")
        self.gridLayout_3.addWidget(self.h_value, 11, 1, 1, 1)
        self.sp_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sp_label.sizePolicy().hasHeightForWidth())
        self.sp_label.setSizePolicy(sizePolicy)
        self.sp_label.setMinimumSize(QtCore.QSize(56, 23))
        self.sp_label.setMaximumSize(QtCore.QSize(200, 15))
        self.sp_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sp_label.setAutoFillBackground(False)
        self.sp_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.sp_label.setFrameShape(QtWidgets.QFrame.Box)
        self.sp_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sp_label.setScaledContents(False)
        self.sp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sp_label.setObjectName("sp_label")
        self.gridLayout_3.addWidget(self.sp_label, 6, 0, 1, 1)
        self.mbr_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mbr_value.sizePolicy().hasHeightForWidth())
        self.mbr_value.setSizePolicy(sizePolicy)
        self.mbr_value.setMinimumSize(QtCore.QSize(56, 23))
        self.mbr_value.setMaximumSize(QtCore.QSize(200, 15))
        self.mbr_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mbr_value.setAutoFillBackground(False)
        self.mbr_value.setInputMethodHints(QtCore.Qt.ImhNone)
        self.mbr_value.setFrameShape(QtWidgets.QFrame.Box)
        self.mbr_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mbr_value.setScaledContents(False)
        self.mbr_value.setAlignment(QtCore.Qt.AlignCenter)
        self.mbr_value.setObjectName("mbr_value")
        self.gridLayout_3.addWidget(self.mbr_value, 5, 1, 1, 1)
        self.pc_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pc_value.sizePolicy().hasHeightForWidth())
        self.pc_value.setSizePolicy(sizePolicy)
        self.pc_value.setMinimumSize(QtCore.QSize(56, 23))
        self.pc_value.setMaximumSize(QtCore.QSize(200, 15))
        self.pc_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pc_value.setAutoFillBackground(False)
        self.pc_value.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pc_value.setFrameShape(QtWidgets.QFrame.Box)
        self.pc_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pc_value.setScaledContents(False)
        self.pc_value.setAlignment(QtCore.Qt.AlignCenter)
        self.pc_value.setObjectName("pc_value")
        self.gridLayout_3.addWidget(self.pc_value, 4, 1, 1, 1)
        self.mdr_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mdr_value.sizePolicy().hasHeightForWidth())
        self.mdr_value.setSizePolicy(sizePolicy)
        self.mdr_value.setMinimumSize(QtCore.QSize(56, 23))
        self.mdr_value.setMaximumSize(QtCore.QSize(200, 15))
        self.mdr_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mdr_value.setAutoFillBackground(False)
        self.mdr_value.setInputMethodHints(QtCore.Qt.ImhNone)
        self.mdr_value.setFrameShape(QtWidgets.QFrame.Box)
        self.mdr_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mdr_value.setScaledContents(False)
        self.mdr_value.setAlignment(QtCore.Qt.AlignCenter)
        self.mdr_value.setObjectName("mdr_value")
        self.gridLayout_3.addWidget(self.mdr_value, 3, 1, 1, 1)
        self.lv_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lv_value.sizePolicy().hasHeightForWidth())
        self.lv_value.setSizePolicy(sizePolicy)
        self.lv_value.setMinimumSize(QtCore.QSize(56, 23))
        self.lv_value.setMaximumSize(QtCore.QSize(200, 15))
        self.lv_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lv_value.setAutoFillBackground(False)
        self.lv_value.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lv_value.setFrameShape(QtWidgets.QFrame.Box)
        self.lv_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lv_value.setScaledContents(False)
        self.lv_value.setAlignment(QtCore.Qt.AlignCenter)
        self.lv_value.setObjectName("lv_value")
        self.gridLayout_3.addWidget(self.lv_value, 7, 1, 1, 1)
        self.pc_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pc_label.sizePolicy().hasHeightForWidth())
        self.pc_label.setSizePolicy(sizePolicy)
        self.pc_label.setMinimumSize(QtCore.QSize(56, 23))
        self.pc_label.setMaximumSize(QtCore.QSize(200, 15))
        self.pc_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pc_label.setAutoFillBackground(False)
        self.pc_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pc_label.setFrameShape(QtWidgets.QFrame.Box)
        self.pc_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pc_label.setScaledContents(False)
        self.pc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pc_label.setObjectName("pc_label")
        self.gridLayout_3.addWidget(self.pc_label, 4, 0, 1, 1)
        self.cpp_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cpp_label.sizePolicy().hasHeightForWidth())
        self.cpp_label.setSizePolicy(sizePolicy)
        self.cpp_label.setMinimumSize(QtCore.QSize(56, 23))
        self.cpp_label.setMaximumSize(QtCore.QSize(200, 15))
        self.cpp_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cpp_label.setAutoFillBackground(False)
        self.cpp_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.cpp_label.setFrameShape(QtWidgets.QFrame.Box)
        self.cpp_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cpp_label.setScaledContents(False)
        self.cpp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cpp_label.setObjectName("cpp_label")
        self.gridLayout_3.addWidget(self.cpp_label, 8, 0, 1, 1)
        self.h_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.h_label.sizePolicy().hasHeightForWidth())
        self.h_label.setSizePolicy(sizePolicy)
        self.h_label.setMinimumSize(QtCore.QSize(56, 23))
        self.h_label.setMaximumSize(QtCore.QSize(200, 15))
        self.h_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.h_label.setAutoFillBackground(False)
        self.h_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.h_label.setFrameShape(QtWidgets.QFrame.Box)
        self.h_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.h_label.setScaledContents(False)
        self.h_label.setAlignment(QtCore.Qt.AlignCenter)
        self.h_label.setObjectName("h_label")
        self.gridLayout_3.addWidget(self.h_label, 11, 0, 1, 1)
        self.mbr_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mbr_label.sizePolicy().hasHeightForWidth())
        self.mbr_label.setSizePolicy(sizePolicy)
        self.mbr_label.setMinimumSize(QtCore.QSize(56, 23))
        self.mbr_label.setMaximumSize(QtCore.QSize(200, 15))
        self.mbr_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mbr_label.setAutoFillBackground(False)
        self.mbr_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.mbr_label.setFrameShape(QtWidgets.QFrame.Box)
        self.mbr_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mbr_label.setScaledContents(False)
        self.mbr_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mbr_label.setObjectName("mbr_label")
        self.gridLayout_3.addWidget(self.mbr_label, 5, 0, 1, 1)
        self.lv_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lv_label.sizePolicy().hasHeightForWidth())
        self.lv_label.setSizePolicy(sizePolicy)
        self.lv_label.setMinimumSize(QtCore.QSize(56, 23))
        self.lv_label.setMaximumSize(QtCore.QSize(200, 15))
        self.lv_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lv_label.setAutoFillBackground(False)
        self.lv_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lv_label.setFrameShape(QtWidgets.QFrame.Box)
        self.lv_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lv_label.setScaledContents(False)
        self.lv_label.setAlignment(QtCore.Qt.AlignCenter)
        self.lv_label.setObjectName("lv_label")
        self.gridLayout_3.addWidget(self.lv_label, 7, 0, 1, 1)
        self.tos_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tos_label.sizePolicy().hasHeightForWidth())
        self.tos_label.setSizePolicy(sizePolicy)
        self.tos_label.setMinimumSize(QtCore.QSize(56, 23))
        self.tos_label.setMaximumSize(QtCore.QSize(200, 15))
        self.tos_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tos_label.setAutoFillBackground(False)
        self.tos_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tos_label.setFrameShape(QtWidgets.QFrame.Box)
        self.tos_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tos_label.setScaledContents(False)
        self.tos_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tos_label.setObjectName("tos_label")
        self.gridLayout_3.addWidget(self.tos_label, 9, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 14, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(169, 15))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 15, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 0, 1, 2)
        self.code_table = QtWidgets.QTableWidget(self.gridLayoutWidget_3)
        self.code_table.setMaximumSize(QtCore.QSize(169, 277))
        self.code_table.setColumnCount(1)
        self.code_table.setObjectName("code_table")
        self.code_table.setRowCount(0)
        self.code_table.horizontalHeader().setVisible(False)
        self.code_table.horizontalHeader().setHighlightSections(True)
        self.code_table.verticalHeader().setVisible(False)
        self.code_table.verticalHeader().setHighlightSections(False)
        self.gridLayout_3.addWidget(self.code_table, 16, 0, 1, 2)
        self.sc_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sc_label.sizePolicy().hasHeightForWidth())
        self.sc_label.setSizePolicy(sizePolicy)
        self.sc_label.setMinimumSize(QtCore.QSize(56, 23))
        self.sc_label.setMaximumSize(QtCore.QSize(200, 15))
        self.sc_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sc_label.setAutoFillBackground(False)
        self.sc_label.setInputMethodHints(QtCore.Qt.ImhNone)
        self.sc_label.setFrameShape(QtWidgets.QFrame.Box)
        self.sc_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sc_label.setScaledContents(False)
        self.sc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sc_label.setObjectName("sc_label")
        self.gridLayout_3.addWidget(self.sc_label, 12, 0, 1, 1)
        self.sc_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sc_value.sizePolicy().hasHeightForWidth())
        self.sc_value.setSizePolicy(sizePolicy)
        self.sc_value.setMinimumSize(QtCore.QSize(56, 23))
        self.sc_value.setMaximumSize(QtCore.QSize(112, 15))
        self.sc_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sc_value.setAutoFillBackground(False)
        self.sc_value.setInputMethodHints(QtCore.Qt.ImhNone)
        self.sc_value.setFrameShape(QtWidgets.QFrame.Box)
        self.sc_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sc_value.setScaledContents(False)
        self.sc_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sc_value.setObjectName("sc_value")
        self.gridLayout_3.addWidget(self.sc_value, 12, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.execute_tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(180, 0, 171, 651))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label.setMaximumSize(QtCore.QSize(169, 15))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_5.setMaximumSize(QtCore.QSize(169, 15))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 3, 0, 1, 1)
        self.lv_table = QtWidgets.QTableWidget(self.gridLayoutWidget_4)
        self.lv_table.setMaximumSize(QtCore.QSize(169, 277))
        self.lv_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lv_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lv_table.setRowCount(0)
        self.lv_table.setColumnCount(2)
        self.lv_table.setObjectName("lv_table")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.lv_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.lv_table.setHorizontalHeaderItem(1, item)
        self.lv_table.horizontalHeader().setDefaultSectionSize(80)
        self.lv_table.horizontalHeader().setMinimumSectionSize(80)
        self.lv_table.verticalHeader().setVisible(False)
        self.lv_table.verticalHeader().setDefaultSectionSize(35)
        self.lv_table.verticalHeader().setMinimumSectionSize(35)
        self.gridLayout_4.addWidget(self.lv_table, 4, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_6.setMaximumSize(QtCore.QSize(169, 15))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.stack_table = QtWidgets.QTableWidget(self.gridLayoutWidget_4)
        self.stack_table.setMaximumSize(QtCore.QSize(169, 277))
        self.stack_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stack_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stack_table.setRowCount(0)
        self.stack_table.setColumnCount(2)
        self.stack_table.setObjectName("stack_table")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.stack_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.stack_table.setHorizontalHeaderItem(1, item)
        self.stack_table.horizontalHeader().setDefaultSectionSize(80)
        self.stack_table.horizontalHeader().setMinimumSectionSize(80)
        self.stack_table.verticalHeader().setVisible(False)
        self.stack_table.verticalHeader().setDefaultSectionSize(35)
        self.stack_table.verticalHeader().setMinimumSectionSize(35)
        self.gridLayout_4.addWidget(self.stack_table, 2, 0, 1, 1)
        self.const_table = QtWidgets.QTableWidget(self.gridLayoutWidget_4)
        self.const_table.setMaximumSize(QtCore.QSize(169, 277))
        self.const_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.const_table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.const_table.setRowCount(0)
        self.const_table.setColumnCount(2)
        self.const_table.setObjectName("const_table")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.const_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.const_table.setHorizontalHeaderItem(1, item)
        self.const_table.horizontalHeader().setDefaultSectionSize(40)
        self.const_table.horizontalHeader().setMinimumSectionSize(12)
        self.const_table.verticalHeader().setVisible(False)
        self.const_table.verticalHeader().setDefaultSectionSize(20)
        self.const_table.verticalHeader().setMinimumSectionSize(20)
        self.gridLayout_4.addWidget(self.const_table, 6, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.execute_tab)
        self.line_4.setGeometry(QtCore.QRect(350, 0, 13, 650))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_3 = QtWidgets.QLabel(self.execute_tab)
        self.label_3.setGeometry(QtCore.QRect(370, -40, 301, 701))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.execute_tab)
        self.label_7.setGeometry(QtCore.QRect(640, 0, 31, 141))
        self.label_7.setObjectName("label_7")
        self.mar_ld = QtWidgets.QLabel(self.execute_tab)
        self.mar_ld.setGeometry(QtCore.QRect(460, 60, 31, 16))
        self.mar_ld.setObjectName("mar_ld")
        self.mdr_ld = QtWidgets.QLabel(self.execute_tab)
        self.mdr_ld.setGeometry(QtCore.QRect(460, 100, 31, 16))
        self.mdr_ld.setObjectName("mdr_ld")
        self.mdr_out = QtWidgets.QLabel(self.execute_tab)
        self.mdr_out.setGeometry(QtCore.QRect(530, 100, 31, 16))
        self.mdr_out.setObjectName("mdr_out")
        self.pc_ld = QtWidgets.QLabel(self.execute_tab)
        self.pc_ld.setGeometry(QtCore.QRect(460, 150, 31, 16))
        self.pc_ld.setObjectName("pc_ld")
        self.pc_out = QtWidgets.QLabel(self.execute_tab)
        self.pc_out.setGeometry(QtCore.QRect(530, 150, 31, 16))
        self.pc_out.setObjectName("pc_out")
        self.mbr_ld = QtWidgets.QLabel(self.execute_tab)
        self.mbr_ld.setGeometry(QtCore.QRect(460, 190, 31, 16))
        self.mbr_ld.setObjectName("mbr_ld")
        self.mbr_out1 = QtWidgets.QLabel(self.execute_tab)
        self.mbr_out1.setGeometry(QtCore.QRect(520, 190, 31, 16))
        self.mbr_out1.setObjectName("mbr_out1")
        self.mbr_out2 = QtWidgets.QLabel(self.execute_tab)
        self.mbr_out2.setGeometry(QtCore.QRect(550, 190, 31, 16))
        self.mbr_out2.setObjectName("mbr_out2")
        self.sp_ld = QtWidgets.QLabel(self.execute_tab)
        self.sp_ld.setGeometry(QtCore.QRect(460, 240, 31, 16))
        self.sp_ld.setObjectName("sp_ld")
        self.sp_out = QtWidgets.QLabel(self.execute_tab)
        self.sp_out.setGeometry(QtCore.QRect(530, 240, 31, 16))
        self.sp_out.setObjectName("sp_out")
        self.lv_ld = QtWidgets.QLabel(self.execute_tab)
        self.lv_ld.setGeometry(QtCore.QRect(460, 280, 31, 16))
        self.lv_ld.setObjectName("lv_ld")
        self.lv_out = QtWidgets.QLabel(self.execute_tab)
        self.lv_out.setGeometry(QtCore.QRect(530, 280, 31, 16))
        self.lv_out.setObjectName("lv_out")
        self.cpp_ld = QtWidgets.QLabel(self.execute_tab)
        self.cpp_ld.setGeometry(QtCore.QRect(460, 320, 31, 16))
        self.cpp_ld.setObjectName("cpp_ld")
        self.cpp_out = QtWidgets.QLabel(self.execute_tab)
        self.cpp_out.setGeometry(QtCore.QRect(530, 320, 31, 16))
        self.cpp_out.setObjectName("cpp_out")
        self.tos_out = QtWidgets.QLabel(self.execute_tab)
        self.tos_out.setGeometry(QtCore.QRect(530, 370, 31, 16))
        self.tos_out.setObjectName("tos_out")
        self.tos_ld = QtWidgets.QLabel(self.execute_tab)
        self.tos_ld.setGeometry(QtCore.QRect(460, 370, 31, 16))
        self.tos_ld.setObjectName("tos_ld")
        self.opc_ld = QtWidgets.QLabel(self.execute_tab)
        self.opc_ld.setGeometry(QtCore.QRect(460, 410, 31, 16))
        self.opc_ld.setObjectName("opc_ld")
        self.opc_out = QtWidgets.QLabel(self.execute_tab)
        self.opc_out.setGeometry(QtCore.QRect(530, 410, 31, 16))
        self.opc_out.setObjectName("opc_out")
        self.H_ld = QtWidgets.QLabel(self.execute_tab)
        self.H_ld.setGeometry(QtCore.QRect(460, 460, 31, 16))
        self.H_ld.setObjectName("H_ld")
        self.tabWidget.addTab(self.execute_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.define_buttons_actions()
        self.signals_stop()
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "execute"))
        self.save_as_btn.setText(_translate("MainWindow", "save as"))
        self.assemble_btn.setText(_translate("MainWindow", "assemble"))
        self.run_btn.setText(_translate("MainWindow", "run"))
        self.open_btn.setText(_translate("MainWindow", "open"))
        self.save_btn.setText(_translate("MainWindow", "save"))
        self.new_btn.setText(_translate("MainWindow", "new"))
        self.step_fwd_btn.setText(_translate("MainWindow", "step fwd"))
        self.main_editor.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:15pt;\"><br /></p></body></html>"))
        self.messages_viewer.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">nothing happened yet!</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.messages_label.setText(_translate("MainWindow", "messages:"))
        self.clear_btn.setText(_translate("MainWindow", "clear"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/Edit_tab.jpg\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.edit_tab), _translate("MainWindow", "edit"))
        self.label_4.setText(_translate("MainWindow", "registers"))
        self.opc_value.setText(_translate("MainWindow", "0x00000000"))
        self.sp_value.setText(_translate("MainWindow", "0x00000000"))
        self.mar_value.setText(_translate("MainWindow", "0x00000000"))
        self.opc_label.setText(_translate("MainWindow", "OPC"))
        self.mdr_label.setText(_translate("MainWindow", "MDR"))
        self.mar_label.setText(_translate("MainWindow", "MAR"))
        self.tos_value.setText(_translate("MainWindow", "0x00000000"))
        self.cpp_value.setText(_translate("MainWindow", "0x00000000"))
        self.h_value.setText(_translate("MainWindow", "0x00000000"))
        self.sp_label.setText(_translate("MainWindow", "SP"))
        self.mbr_value.setText(_translate("MainWindow", "0x00000000"))
        self.pc_value.setText(_translate("MainWindow", "0x00000000"))
        self.mdr_value.setText(_translate("MainWindow", "0x00000000"))
        self.lv_value.setText(_translate("MainWindow", "0x00000000"))
        self.pc_label.setText(_translate("MainWindow", "PC"))
        self.cpp_label.setText(_translate("MainWindow", "CPP"))
        self.h_label.setText(_translate("MainWindow", "H"))
        self.mbr_label.setText(_translate("MainWindow", "MBR"))
        self.lv_label.setText(_translate("MainWindow", "LV"))
        self.tos_label.setText(_translate("MainWindow", "TOS"))
        self.label_2.setText(_translate("MainWindow", "codes"))
        self.sc_label.setText(_translate("MainWindow", "SC"))
        self.sc_value.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "constants"))
        self.label_5.setText(_translate("MainWindow", "local variables"))
        item = self.lv_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "label"))
        item = self.lv_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "value"))
        self.label_6.setText(_translate("MainWindow", "stack"))
        item = self.stack_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "label"))
        item = self.stack_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "value"))
        item = self.const_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "label"))
        item = self.const_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "value"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/datapath_50p.png\"/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/Execute_tab.jpg\"/></p></body></html>"))
        self.mar_ld.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.mdr_ld.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.mdr_out.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.pc_ld.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.pc_out.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.mbr_ld.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.mbr_out1.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.mbr_out2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.sp_ld.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.sp_out.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.lv_ld.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.lv_out.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.cpp_ld.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.cpp_out.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.tos_out.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.tos_ld.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.opc_ld.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.opc_out.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.H_ld.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"graphics/datapath design/arrow_green.png\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.execute_tab), _translate("MainWindow", "execute"))

    def define_buttons_actions(self):
        self.new_btn.clicked.connect(new_btn_clicked)
        self.open_btn.clicked.connect(self.open_btn_clicked)
        self.save_btn.clicked.connect(self.save_btn_clicked)
        self.save_as_btn.clicked.connect(save_as_btn_clicked)
        self.assemble_btn.clicked.connect(self.assemble_btn_clicked)
        self.run_btn.clicked.connect(run_btn_clicked)
        self.step_fwd_btn.clicked.connect(step_fwd_btn_clicked)
        self.clear_btn.clicked.connect(self.clear_btn_clicked)
        # todo baraie slide bar ham baiad ezafe she

    def clear_btn_clicked(self):
        self.messages_viewer.clear()

    def save_btn_clicked(self):
        save_btn_clicked(self.main_editor.toPlainText())

    def open_btn_clicked(self):
        self.main_editor.setText(open_btn_clicked())

    def assemble_btn_clicked(self):
        asm = open("codes/deafult_input_assembly.txt", "r").read().split("\n")
        text = asm[asm.index(".text")+1:asm.index(".end_text")]
        const = asm[asm.index(".consts")+1:asm.index(".end_consts")]
        vars = asm[asm.index(".vars")+1:asm.index(".end_vars")]
        for i in range(self.code_table.rowCount()):
            self.code_table.removeRow(0)
        for i in range(self.const_table.rowCount()):
            self.const_table.removeRow(0)
        for i in range(self.lv_table.rowCount()):
            self.lv_table.removeRow(0)
        for i in text:
            row_position = self.code_table.rowCount()
            self.code_table.insertRow(row_position)
            self.code_table.setItem(row_position, 0, QtWidgets.QTableWidgetItem(i))
        for i in const:
            row_position = self.const_table.rowCount()
            self.const_table.insertRow(row_position)
            self.const_table.setItem(row_position, 0, QtWidgets.QTableWidgetItem(i.split()[0][:-1]))
            self.const_table.setItem(row_position, 1, QtWidgets.QTableWidgetItem(i.split()[1]))
        for i in vars:
            row_position = self.lv_table.rowCount()
            self.lv_table.insertRow(row_position)
            self.lv_table.setItem(row_position, 0, QtWidgets.QTableWidgetItem(i.split()[0][:-1]))
            self.lv_table.setItem(row_position, 1, QtWidgets.QTableWidgetItem(i.split()[1]))
        self.tabWidget.setCurrentIndex(1)
        self.messages_viewer.setText(self.messages_viewer.toPlainText()+"\n\n" + "assembled successfully")
        assemble_btn_clicked()

    def mar_ld_start(self, value):
        self.mar_value.setText("0x" + ("0"*(8 - len(hex(value)[2:]))) + hex(value)[2:])
        self.mar_ld.show()

    def mdr_ld_start(self, value):
        self.mdr_value.setText("0x" + ("0"*(8 - len(hex(value)[2:]))) + hex(value)[2:])
        self.mdr_ld.show()

    def mdr_out_start(self):
        self.mdr_out.show()

    def pc_ld_start(self, value):
        self.pc_value.setText("0x" + ("0"*(8 - len(hex(value)[2:]))) + hex(value)[2:])
        self.pc_ld.show()

    def pc_out_start(self):
        self.pc_out.show()

    def mbr_ld_start(self, value):
        self.mbr_value.setText("0x" + ("0"*(8 - len(hex(value)[2:]))) + hex(value)[2:])
        self.mbr_ld.show()

    def mbr_out1_start(self):
        self.mbr_out1.show()

    def mbr_out2_start(self):
        self.mbr_out2.show()

    def sp__ld_start(self, value):
        self.sp_value.setText("0x" + ("0"*(8 - len(hex(value)[2:]))) + hex(value)[2:])
        self.sp_ld.show()

    def sp_out_start(self):
        self.sp_out.show()

    def cpp_ld_start(self, value):
        self.cpp_value.setText("0x" + ("0"*(8 - len(hex(value)[2:]))) + hex(value)[2:])
        self.cpp_ld.show()

    def cpp_out_start(self):
        self.cpp_out.show()

    def lv_ld_start(self, value):
        self.lv_value.setText("0x" + ("0"*(8 - len(hex(value)[2:]))) + hex(value)[2:])
        self.lv_ld.show()

    def lv_out_start(self):
        self.lv_out.show()

    def tos_ld_start(self, value):
        self.tos_value.setText("0x" + ("0"*(8 - len(hex(value)[2:]))) + hex(value)[2:])
        self.tos_ld.show()

    def tos_out_start(self):
        self.tos_out.show()

    def opc_ld_start(self, value):
        self.opc_value.setText("0x" + ("0"*(8 - len(hex(value)[2:]))) + hex(value)[2:])
        self.opc_ld.show()

    def opc_out_start(self):
        self.opc_out.show()

    def h_ld_start(self, value):
        self.h_value.setText("0x" + ("0"*(8 - len(hex(value)[2:]))) + hex(value)[2:])
        self.H_ld.show()

    def signals_stop(self):
        self.mar_ld.hide()
        self.mdr_ld.hide()
        self.mdr_out.hide()
        self.pc_ld.hide()
        self.pc_out.hide()
        self.mbr_ld.hide()
        self.mbr_out1.hide()
        self.mbr_out2.hide()
        self.sp_ld.hide()
        self.sp_out.hide()
        self.cpp_ld.hide()
        self.cpp_out.hide()
        self.lv_ld.hide()
        self.lv_out.hide()
        self.tos_ld.hide()
        self.tos_out.hide()
        self.opc_ld.hide()
        self.opc_out.hide()
        self.H_ld.hide()
